function button_7 () { // функция Try ... Catch

try {
    const a = 10;
    a = a+10;
    alert(a) 
  } 
  catch (err) {
    alert("Ошибка!!!") // вывод при обнаружении ошибки
  }
  
}